### ISSUE TITLE
Move some search functionality into Search from SearchHandler 

### ISSUE THREAD

**Issue by PeterGardenas** [Yeetii/ProjektgruppLP4#78]
Should be some functionality in Search, also makes it testable.

**Comment by FlexTerror** [comment]
Why shouldn't SearchHandler hold all the searching functionality? Isn't the Search object just to be a model of the searching criteria and the handler is suppose to be it "controller"?

**Comment by FlexTerror** [comment]
The "isNotNull()" in SearchHandler has been moved to Search and renamed "isEmpty()" and now has a inverse return.
